# NeuPrint API Tutorial and Testing

In [1]:
import numpy as np
import pandas as pd

import bokeh
import hvplot.pandas
import holoviews as hv

import bokeh.palettes
from bokeh.plotting import figure, show, output_notebook

In [2]:
!jupyter nbextension enable --py widgetsnbextension

usage: jupyter [-h] [--version] [--config-dir] [--data-dir] [--runtime-dir]
               [--paths] [--json] [--debug]
               [subcommand]

Jupyter: Interactive Computing

positional arguments:
  subcommand     the subcommand to launch

options:
  -h, --help     show this help message and exit
  --version      show the versions of core jupyter packages and exit
  --config-dir   show Jupyter config dir
  --data-dir     show Jupyter data dir
  --runtime-dir  show Jupyter runtime dir
  --paths        show all Jupyter paths. Add --json for machine-readable
                 format.
  --json         output paths as machine-readable json
  --debug        output debug information about paths

Available subcommands: console contrib dejavu events execute kernel kernelspec
lab labextension labhub migrate nbclassic nbconvert nbextensions_configurator
notebook qtconsole run server troubleshoot trust

Jupyter command `jupyter-nbextension` not found.

In [5]:
import neuprint

In [6]:
TOKEN = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6Imt5bGllaHVjaEBiZXJrZWxleS5lZHUiLCJsZXZlbCI6Im5vYXV0aCIsImltYWdlLXVybCI6Imh0dHBzOi8vbGgzLmdvb2dsZXVzZXJjb250ZW50LmNvbS9hL0FDZzhvY0tpVkJGeHFzT1JxRlhnNnNOX0xIWnd4RjRoWDJORWh4WFBpY2hDaEV1Qjdsei0yUT1zOTYtYz9zej01MD9zej01MCIsImV4cCI6MTkyMjI1NDAyMH0.WLushXPCMuxMHltv_LUpoVmhtGyZSTZw08ShIrEboLY"

c = neuprint.Client('neuprint.janelia.org', 'hemibrain:v1.2.1', TOKEN)

## Conectivity Queries

In [8]:
#s_cri_0 = neuprint.NeuronCriteria(type='Delta*', status='Traced', cropped=False)
s_cri_0 = neuprint.NeuronCriteria(instance='Delta7(PB15)_L4R5_R')
neuron_df, roi_counts_df = neuprint.fetch_neurons(s_cri_0)

print(neuron_df[['bodyId', 'instance', 'type', 'pre', 'post', 'status', 'cropped', 'size']])

      bodyId             instance    type  pre  post  status  cropped  \
0  880880259  Delta7(PB15)_L4R5_R  Delta7  546  1208  Traced    False
1  910442723  Delta7(PB15)_L4R5_R  Delta7  525  1157  Traced    False
2  911129339  Delta7(PB15)_L4R5_R  Delta7  523  1045  Traced    False
3  911134009  Delta7(PB15)_L4R5_R  Delta7  534  1125  Traced    False
4  911138168  Delta7(PB15)_L4R5_R  Delta7  540  1054  Traced    False

         size
0  1316285121
1  1117687707
2  1253944757
3  1154421327
4  1208668943

In [9]:
# Data frames are pandas DataFrame objects
print(type(roi_counts_df))
print(roi_counts_df)
print()

# Access a group of rows and columns by label(s) or a boolean array
print(roi_counts_df.loc[0:3])
filtered_df = roi_counts_df[roi_counts_df['bodyId']==880880259]
print(filtered_df)

<class 'pandas.core.frame.DataFrame'>
        bodyId         roi  pre  post  downstream  upstream  mito
0    880880259          CX  544  1202        4957      1202   259
1    880880259  NotPrimary    2     6           6         6   109
2    880880259          PB  544  1202        4957      1202   259
3    880880259      PB(L1)    5   103          22       103    18
4    880880259      PB(L2)    2    59          14        59     4
..         ...         ...  ...   ...         ...       ...   ...
102  911138168      PB(R5)  222    55        2060        55    34
103  911138168      PB(R6)    6    31          44        31     9
104  911138168      PB(R7)    0    46           0        46    13
105  911138168      PB(R8)    2    92           6        92    11
106  911138168      PB(R9)    0    23           0        23     5

[107 rows x 7 columns]

      bodyId         roi  pre  post  downstream  upstream  mito
0  880880259          CX  544  1202        4957      1202   259
1  880880259  NotPrimary    2     6           6         6   109
2  880880259          PB  544  1202        4957      1202   259
3  880880259      PB(L1)    5   103          22       103    18
       bodyId         roi  pre  post  downstream  upstream  mito
0   880880259          CX  544  1202        4957      1202   259
1   880880259  NotPrimary    2     6           6         6   109
2   880880259          PB  544  1202        4957      1202   259
3   880880259      PB(L1)    5   103          22       103    18
4   880880259      PB(L2)    2    59          14        59     4
5   880880259      PB(L3)    2    66           8        66     8
6   880880259      PB(L4)  116    66        1104        66    24
7   880880259      PB(L5)  145    63        1369        63    14
8   880880259      PB(L6)    2    31           6        31     6
9   880880259      PB(L7)    0    53           0        53    10
10  880880259      PB(L8)    0    67           0        67    22
11  880880259      PB(L9)    0    46           0        46    11
12  880880259      PB(R1)    3   115           9       115    11
13  880880259      PB(R2)    2    88           6        88     7
14  880880259      PB(R3)    2   131           6       131    13
15  880880259      PB(R4)    0    38           0        38    10
16  880880259      PB(R5)  261    57        2403        57    44
17  880880259      PB(R6)    1    33           1        33    19
18  880880259      PB(R7)    1    65           4        65     8
19  880880259      PB(R8)    2   101           5       101    25
20  880880259      PB(R9)    0    20           0        20     5

In [10]:
upstream = neuprint.NeuronCriteria(instance='Delta7(PB15)_L4R5_R')
downstream = neuprint.NeuronCriteria(type='PEN.*')
neuron_df, conn_df = neuprint.fetch_adjacencies(upstream, downstream)

print(neuron_df)

        bodyId         type             instance
0    880880259       Delta7  Delta7(PB15)_L4R5_R
1    910442723       Delta7  Delta7(PB15)_L4R5_R
2    911129339       Delta7  Delta7(PB15)_L4R5_R
3    911134009       Delta7  Delta7(PB15)_L4R5_R
4    911138168       Delta7  Delta7(PB15)_L4R5_R
5    387023620  PEN_b(PEN2)      PEN_b(PB06b)_L4
6    509410587  PEN_a(PEN1)      PEN_a(PB06a)_R4
7    539462336  PEN_b(PEN2)      PEN_b(PB06b)_L4
8    569775058  PEN_b(PEN2)      PEN_b(PB06b)_R4
9    570461892  PEN_a(PEN1)      PEN_a(PB06a)_R3
10   634608104  PEN_a(PEN1)      PEN_a(PB06a)_L2
11   663190769  PEN_a(PEN1)      PEN_a(PB06a)_R6
12   663562172  PEN_b(PEN2)      PEN_b(PB06b)_R4
13   693755250  PEN_b(PEN2)      PEN_b(PB06b)_R7
14   724280817  PEN_b(PEN2)      PEN_b(PB06b)_R2
15   757055317  PEN_a(PEN1)      PEN_a(PB06a)_L4
16   847336755  PEN_a(PEN1)      PEN_a(PB06a)_R6
17   849421763  PEN_b(PEN2)      PEN_b(PB06b)_R5
18   849482511  PEN_a(PEN1)      PEN_a(PB06a)_L4
19   910447075  PEN_a(PEN1)      PEN_a(PB06a)_R5
20   941123755  PEN_b(PEN2)      PEN_b(PB06b)_R6
21   972892437  PEN_a(PEN1)      PEN_a(PB06a)_R2
22   973566036  PEN_b(PEN2)      PEN_b(PB06b)_R3
23  1002507131  PEN_a(PEN1)      PEN_a(PB06a)_R7
24  1062526223  PEN_b(PEN2)      PEN_b(PB06b)_R8
25  1125964630  PEN_a(PEN1)      PEN_a(PB06a)_R8
26  1197993940  PEN_b(PEN2)      PEN_b(PB06b)_R6
27  1631450739  PEN_b(PEN2)      PEN_b(PB06b)_L5
28  5813056953  PEN_a(PEN1)      PEN_a(PB06a)_R4
29  5813080979  PEN_a(PEN1)      PEN_a(PB06a)_L5

In [11]:
print(conn_df.sort_values('weight', ascending=False))

    bodyId_pre  bodyId_post roi  weight
4    880880259    849421763  PB     141
22   910442723    849421763  PB     139
56   911134009    849421763  PB     125
40   911129339    849421763  PB     108
69   911138168    849421763  PB     107
..         ...          ...  ..     ...
16   910442723    663190769  PB       1
8    880880259   1125964630  PB       1
73   911138168   1125964630  PB       1
75   911138168   1631450739  PB       1
76   911138168   5813056953  PB       1

[77 rows x 4 columns]

In [12]:
conn_df = neuprint.merge_neuron_properties(neuron_df, conn_df, ['type', 'instance'])
print(conn_df)

    bodyId_pre  bodyId_post roi  weight type_pre         instance_pre  \
0    880880259    387023620  PB      69   Delta7  Delta7(PB15)_L4R5_R
1    880880259    539462336  PB      11   Delta7  Delta7(PB15)_L4R5_R
2    880880259    634608104  PB       1   Delta7  Delta7(PB15)_L4R5_R
3    880880259    757055317  PB      23   Delta7  Delta7(PB15)_L4R5_R
4    880880259    849421763  PB     141   Delta7  Delta7(PB15)_L4R5_R
..         ...          ...  ..     ...      ...                  ...
72   911138168    941123755  PB       2   Delta7  Delta7(PB15)_L4R5_R
73   911138168   1125964630  PB       1   Delta7  Delta7(PB15)_L4R5_R
74   911138168   1197993940  PB       2   Delta7  Delta7(PB15)_L4R5_R
75   911138168   1631450739  PB       1   Delta7  Delta7(PB15)_L4R5_R
76   911138168   5813056953  PB       1   Delta7  Delta7(PB15)_L4R5_R

      type_post    instance_post
0   PEN_b(PEN2)  PEN_b(PB06b)_L4
1   PEN_b(PEN2)  PEN_b(PB06b)_L4
2   PEN_a(PEN1)  PEN_a(PB06a)_L2
3   PEN_a(PEN1)  PEN_a(PB06a)_L4
4   PEN_b(PEN2)  PEN_b(PB06b)_R5
..          ...              ...
72  PEN_b(PEN2)  PEN_b(PB06b)_R6
73  PEN_a(PEN1)  PEN_a(PB06a)_R8
74  PEN_b(PEN2)  PEN_b(PB06b)_R6
75  PEN_b(PEN2)  PEN_b(PB06b)_L5
76  PEN_a(PEN1)  PEN_a(PB06a)_R4

[77 rows x 8 columns]

In [13]:
inst_conn_mx = neuprint.utils.connection_table_to_matrix(conn_df, 'instance', sort_by='type')
print(inst_conn_mx)

instance_post        PEN_a(PB06a)_L4  PEN_a(PB06a)_L5  PEN_a(PB06a)_R3  \
instance_pre
Delta7(PB15)_L4R5_R              267               21                2

instance_post        PEN_a(PB06a)_R6  PEN_a(PB06a)_R5  PEN_a(PB06a)_R4  \
instance_pre
Delta7(PB15)_L4R5_R               54              145               11

instance_post        PEN_a(PB06a)_R7  PEN_a(PB06a)_R8  PEN_a(PB06a)_R2  \
instance_pre
Delta7(PB15)_L4R5_R                1                3                3

instance_post        PEN_a(PB06a)_L2  PEN_b(PB06b)_R2  PEN_b(PB06b)_L4  \
instance_pre
Delta7(PB15)_L4R5_R                1                2              629

instance_post        PEN_b(PB06b)_R6  PEN_b(PB06b)_R5  PEN_b(PB06b)_R4  \
instance_pre
Delta7(PB15)_L4R5_R              127              620               19

instance_post        PEN_b(PB06b)_L5  PEN_b(PB06b)_R8  PEN_b(PB06b)_R7  \
instance_pre
Delta7(PB15)_L4R5_R               87                1                1

instance_post        PEN_b(PB06b)_R3
instance_pre
Delta7(PB15)_L4R5_R                1

In [14]:
id_conn_mx = neuprint.utils.connection_table_to_matrix(conn_df, 'bodyId', sort_by='type')
print(id_conn_mx)

bodyId_post  757055317   5813080979  570461892   663190769   847336755   \
bodyId_pre
880880259            23          13           0           0           0
911134009            22           0           1           9          12
911129339            44           1           1          17          13
911138168            17           0           0           0           1
910442723            42           7           0           1           1

bodyId_post  849482511   910447075   509410587   1002507131  1125964630  ...  \
bodyId_pre                                                               ...
880880259            19          45           0           0           1  ...
911134009            30          25           1           0           1  ...
911129339            11          16           0           0           0  ...
911138168            41          22           6           0           1  ...
910442723            18          37           3           1           0  ...

bodyId_post  1197993940  849421763   539462336   569775058   663562172   \
bodyId_pre
880880259             2         141          11           0           0
911134009            15         125          94           0           0
911129339            34         108          66           0           1
911138168             2         107          67          10           3
910442723             5         139          53           3           2

bodyId_post  1631450739  1062526223  941123755   693755250   973566036
bodyId_pre
880880259            42           0           0           0           0
911134009             0           0          33           0           0
911129339             3           0          34           0           1
911138168             1           0           2           0           0
910442723            41           1           0           1           0

[5 rows x 25 columns]

### Conectivity Visualization

In [85]:
id_conn_mx.index = id_conn_mx.index.astype(str)
id_conn_mx.colums = id_conn_mx.columns.astype(str)
id_conn_mx.hvplot.heatmap(height=200, width=700, xaxis='top').opts(xrotation=60)

:HeatMap   [columns,index]   (value)

In [86]:
inst_conn_mxp = neuprint.utils.connection_table_to_matrix(conn_df, ('instance_pre', 'instance_post'))
inst_conn_mxp.index = inst_conn_mxp.index.astype(str)
inst_conn_mxp.columns = inst_conn_mxp.columns.astype(str)
inst_conn_mxp.hvplot.heatmap(height=200, width=700).opts(xrotation=60)

:HeatMap   [columns,index]   (value)

## Synapse Queries and Visualization

In [17]:
p_syn_c = neuprint.SynapseCriteria(rois='PB', type='pre', primary_only=True)
ps = neuprint.fetch_synapses(upstream, p_syn_c)

p = figure()
p.scatter(ps['x'], ps['z'])
p.y_range.flipped = True
show(p)

In [19]:
syn_c = neuprint.SynapseCriteria(rois='PB', type='post', primary_only=True)
ps = neuprint.fetch_synapses(upstream, syn_c)

p = figure()
p.scatter(ps['x'], ps['z'])
p.y_range.flipped = True
show(p)

In [58]:
pre_nc = neuprint.NeuronCriteria(instance='Delta7(PB15)_L4R5_R')
#post_nc = neuprint.NeuronCriteria(instance='PEN_b(PB06b)_L4')
post_nc = neuprint.NeuronCriteria(type='PEN_b.*')
sc = neuprint.SynapseCriteria(rois=['PB', 'EB'], primary_only=True)
d7_penbl4_conns = neuprint.fetch_synapse_connections(pre_nc, post_nc, sc)
d7_penbl4_conns.head()

  0%|          | 0/1484 [00:00<?, ?it/s]

,bodyId_pre,bodyId_post,roi_pre,roi_post,x_pre,y_pre,z_pre,x_post,y_post,z_post,confidence_pre,confidence_post
0,880880259,849421763,PB,PB,21152,13762,14059,21152,13774,14066,0.992,0.720183
1,880880259,849421763,PB,PB,21115,13775,14062,21120,13754,14076,0.879,0.450640
2,880880259,849421763,PB,PB,20792,14140,13745,20790,14158,13759,0.920,0.907778
3,880880259,849421763,PB,PB,20167,13788,13238,20175,13808,13230,0.967,0.918931
4,880880259,849421763,PB,PB,20950,13826,13876,20961,13815,13896,0.944,0.828105

In [25]:
post_neurons, _ = neuprint.fetch_neurons(d7_penbl4_conns['bodyId_post'].unique())
d7_penbl4_conns_un = neuprint.utils.merge_neuron_properties(post_neurons, d7_penbl4_conns, 'instance')

top5_cnts = d7_penbl4_conns_un['instance_post'].value_counts().head(5)
print(top5_cnts)

instance_post
PEN_b(PB06b)_L4    626
PEN_b(PB06b)_R5    620
PEN_b(PB06b)_R6    127
PEN_b(PB06b)_L5     87
PEN_b(PB06b)_R4     19
Name: count, dtype: int64

In [83]:
conn_vals = d7_penbl4_conns_un['instance_post'].value_counts()
print(post_neurons['instance'].unique())
print(conn_vals)
print(len(post_neurons['instance'].unique()))
print(len(conn_vals))

['PEN_b(PB06b)_L4' 'PEN_b(PB06b)_R4' 'PEN_b(PB06b)_R7' 'PEN_b(PB06b)_R2'
 'PEN_b(PB06b)_R5' 'PEN_b(PB06b)_R6' 'PEN_b(PB06b)_R3' 'PEN_b(PB06b)_R8'
 'PEN_b(PB06b)_L5']
instance_post
PEN_b(PB06b)_L4    626
PEN_b(PB06b)_R5    620
PEN_b(PB06b)_R6    127
PEN_b(PB06b)_L5     87
PEN_b(PB06b)_R4     19
PEN_b(PB06b)_R2      2
PEN_b(PB06b)_R7      1
PEN_b(PB06b)_R8      1
PEN_b(PB06b)_R3      1
Name: count, dtype: int64
9
9

In [75]:
colormap = dict(zip(top5_cnts.index, bokeh.palettes.Category10[5]))
points = d7_penbl4_conns_un.query('instance_post in @top5_cnts.index').copy()
points['color'] = points['instance_post'].map(colormap)

p = figure()
p.scatter(points['x_post'], points['z_post'], color=points['color'])
p.y_range.flipped = True
show(p)

In [76]:
print(points['color'])

0       #ff7f0e
1       #ff7f0e
2       #ff7f0e
3       #ff7f0e
4       #ff7f0e
         ...
1479    #1f77b4
1480    #1f77b4
1481    #d62728
1482    #2ca02c
1483    #2ca02c
Name: color, Length: 1479, dtype: object

## Skeleton Queries and Visualization

In [55]:
# Download some skeletons as DataFrames and attach columns for bodyId and color
skeletons = []
for i, body_Id in enumerate(d7_penbl4_conns_un['bodyId_post'].unique()[:5]):
    s = c.fetch_skeleton(body_Id, format='pandas')
    s['bodyId'] = body_Id
    s['color'] = bokeh.palettes.Accent[5][i]
    skeletons.append(s)

# Combine into one big table for convenient processing
skeletons = pd.concat(skeletons, ignore_index=True)
skeletons.head()

,rowId,x,y,z,radius,link,bodyId,color
0,1,23170.000000,17466.000000,6606.000000,21.000000,-1,849421763,#7fc97f
1,2,23128.000000,17508.000000,6620.000000,55.609901,1,849421763,#7fc97f
2,3,23030.000000,17522.000000,6592.000000,63.000000,2,849421763,#7fc97f
3,4,22868.900391,17511.500000,6531.979980,170.186996,3,849421763,#7fc97f
4,5,22854.800781,17518.599609,6439.930176,207.776993,4,849421763,#7fc97f

In [56]:
# Join parent/child nodes for plotting as line segments below.
# (Using each row's 'link' (parent) ID, find the row with matching rowId.)
segments = skeletons.merge(skeletons, 'inner', left_on=['bodyId', 'link'], right_on=['bodyId', 'rowId'], suffixes=['_child', '_parent'])

p = figure()
p.y_range.flipped = True

# plot skeleton segments (in 2D)
p.segment(x0='x_child', x1='x_parent', y0='z_child', y1='z_parent', color='color_child', source=segments)
p.scatter(points['x_post'], points['z_post'], color=points['color'])
show(p)